[build]
builder = "NIXPACKS"
buildCommand = "pnpm --filter @little-pieces/api build:railway"

[deploy]
startCommand = "pnpm --filter @little-pieces/api start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 100
